ROOT_INITIAL_WIDTH = 1366
ROOT_INITIAL_HEIGHT = 786

PIANO_ROLL_WIDTH_PERCENT = 80
PIANO_ROLL_HEIGHT_PERCENT = 75
CANVAS_GRID_X = 2
CANVAS_GRID_Y = 2
MIN_ZOOM = 0.1
MAX_ZOOM = 20

NOTE_THICKNESS = 25

SIDEBAR_PIANO_WIDTH_PERCENT = 7
SIDEBAR_PIANO_HEIGHT_PERCENT = PIANO_ROLL_HEIGHT_PERCENT

MUSIC_PLAYER_WIDTH_PERCENT = PIANO_ROLL_WIDTH_PERCENT + SIDEBAR_PIANO_WIDTH_PERCENT
MUSIC_PLAYER_HEIGHT_PERCENT = 10

TRACKS_SIDEBAR_WIDTH_PERCENT = 8
TRACKS_SIDEBAR_HEIGHT_PERCENT = SIDEBAR_PIANO_HEIGHT_PERCENT


COLOR_PALETTE = {
    'honeydew': '#F1FFE7',
    'mint_cream': '#F4FFFD',
    'aero_blue': '#C2E7DA',
    'blue_gray': '#6290C3',
    'space_cadet': '#1A1B41',
    'bitter_lime': '#BAFF29',
    'nickel': '#6A706E',
    'naples_yellow': '#F9DC5C',
    'black_coral': '#465362'
}
