ROOT_INITIAL_WIDTH = 1366
ROOT_INITIAL_HEIGHT = 786

PIANO_ROLL_WIDTH_PERCENT = 80
PIANO_ROLL_HEIGHT_PERCENT = 75
CANVAS_GRID_X = 2
CANVAS_GRID_Y = 2

NOTE_THICKNESS = 20

SIDEBAR_PIANO_WIDTH_PERCENT = 5
SIDEBAR_PIANO_HEIGHT_PERCENT = PIANO_ROLL_HEIGHT_PERCENT
